"""
Build app/evals/fix_harness_split.json: the evolve / held-out split for
evolving FixGenerationAgent's harness, in the same shape as harness_split.json
(the diagnosis split) so scripts/optimize_harness.py can use either.

Only cases whose run-1 diagnosis localized (the fix evaluator reuses those
diagnoses and refuses the rest). Outcomes come from run 1 (all500-run1, before
the cut-off fix) and run 2 (all500-run2, after it):

- held out: every localized case in pydata/xarray and sphinx-doc/sphinx, the
  same held-out repos as the diagnosis optimizer; never shown to the proposer.
- evolve "failing": cases resolved in exactly one of runs 1 and 2. The fix
  step is noisy on these, so a harness change can tip them; they carry the signal.
- evolve "hard": a deterministic, evenly spaced sample of cases that failed in
  both runs (room to improve, mostly harder).
- evolve "guards": cases resolved in both, one per repo where possible, to
  catch a candidate that breaks the easy path.

Deterministic: sorted ids, evenly spaced picks. Rerunning gives the same file.
"""
from __future__ import annotations

import glob
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RUN1 = ROOT / "runs" / "fix" / "all500-run1"
RUN2 = ROOT / "runs" / "fix" / "all500-run2"
OUT = ROOT / "app" / "evals" / "fix_harness_split.json"
HELDOUT_REPOS = ["pydata/xarray", "sphinx-doc/sphinx"]
N_HARD = 30
N_GUARDS = 6


def _resolved(run_dir: Path, run_id: str) -> set[str]:
    out = set()
    for f in glob.glob(str(run_dir / "grading" / "logs" / "run_evaluation" / run_id / "*" / "*" / "report.json")):
        out |= {k for k, v in json.loads(Path(f).read_text()).items() if v.get("resolved")}
    return out


def _spaced(items: list[str], n: int) -> list[str]:
    items = sorted(items)
    if len(items) <= n:
        return items
    return [items[int(k * len(items) / n)] for k in range(n)]


def build() -> dict:
    recs = [json.loads(line) for line in (RUN1 / "results.jsonl").read_text().splitlines()]
    localized = {r["instance_id"]: r["repo"] for r in recs if (r.get("diagnosis") or {}).get("verdict") == "PASS"}
    r1, r2 = _resolved(RUN1, "all500-run1"), _resolved(RUN2, "all500-run2")

    held = {c for c, repo in localized.items() if repo in HELDOUT_REPOS}
    pool = sorted(set(localized) - held)
    failing = [c for c in pool if (c in r1) != (c in r2)]
    both_fail = [c for c in pool if c not in r1 and c not in r2]
    both_pass = [c for c in pool if c in r1 and c in r2]

    guards, seen_repos = [], set()
    for c in _spaced(both_pass, len(both_pass)):
        if localized[c] not in seen_repos and len(guards) < N_GUARDS:
            guards.append(c)
            seen_repos.add(localized[c])
    hard = _spaced(both_fail, N_HARD)

    stats = {c: {"repo": localized[c], "run1_resolved": c in r1, "run2_resolved": c in r2}
             for c in sorted(localized)}
    return {
        "_doc": ("Evolve / held-out split for harness evolution on FixGenerationAgent. Generated by "
                 "scripts/build_fix_split.py from fix runs 1 and 2; do not edit by hand. Only cases whose "
                 "run-1 diagnosis localized. See the builder's docstring for the design."),
        "heldout_repos": HELDOUT_REPOS,
        "evolve": {"failing": failing, "hard": hard, "guards": guards},
        "heldout": {"failing": sorted(c for c in held if not (c in r1 and c in r2)),
                    "stable": sorted(c for c in held if c in r1 and c in r2), "hard": []},
        "case_stats": stats,
    }


if __name__ == "__main__":
    split = build()
    OUT.write_text(json.dumps(split, indent=1) + "\n")
    e, h = split["evolve"], split["heldout"]
    print(f"wrote {OUT}: evolve {len(e['failing'])} in-between + {len(e['hard'])} hard + "
          f"{len(e['guards'])} guards; held-out {len(h['failing']) + len(h['stable'])} "
          f"({len(h['stable'])} resolved in both runs)")
